# Generated by Django 4.2.1 on 2023-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenDeTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
