# Generated by Django 4.2.1 on 2023-06-14 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0006_sucursalpart_sucursal_parts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.vehiclesucursal')),
            ],
            options={
                'db_table': 'quotation_request',
            },
        ),
        migrations.CreateModel(
            name='AssignedQuotationRequest',
            fields=[
                ('quotation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cotizacion.quotationrequest')),
                ('finished', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assigned_quotation_request',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installments', models.PositiveSmallIntegerField()),
                ('initial_fee', models.PositiveIntegerField()),
                ('quota_value', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('assigned_quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.assignedquotationrequest')),
            ],
        ),
    ]
