# Generated by Django 4.2.1 on 2023-06-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotation',
            table='quotation',
        ),
    ]
