# Generated by Django 4.2.1 on 2023-06-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_delete_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequest',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='vehicle_sucursal',
        ),
        migrations.DeleteModel(
            name='AssignedQuotationRequest',
        ),
        migrations.DeleteModel(
            name='QuotationRequest',
        ),
    ]
