# Generated by Django 4.2.1 on 2023-06-17 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sucursal', '0006_sucursalpart_sucursal_parts'),
        ('cotizacion', '0004_remove_quotationrequest_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installments', models.PositiveSmallIntegerField()),
                ('initial_fee', models.PositiveIntegerField()),
                ('quota_value', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.vehiclesucursal')),
            ],
        ),
    ]
