# Generated by Django 4.2.1 on 2023-06-17 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotation',
            table='quotation',
        ),
        migrations.CreateModel(
            name='AssignedQuote',
            fields=[
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cotizacion.quotation')),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('FINISHED', 'FINISHED')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assigned_quote',
            },
        ),
    ]
