# Generated by Django 4.2.1 on 2023-06-28 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0007_alter_assignedquote_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedquote',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_quote', to=settings.AUTH_USER_MODEL),
        ),
    ]
