# Generated by Django 4.2.1 on 2023-05-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('modelo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('carroceria', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'Suv'), ('CROSSOVER', 'Crossover'), ('FURGONETA', 'Furgoneta')], max_length=50)),
                ('puertas', models.PositiveSmallIntegerField()),
                ('motor', models.CharField(choices=[('SIP', 'Motor Electrico Sincrono de Imanes Permanentes'), ('CC', 'Motor Electrico de Corriente Continua'), ('I', 'Motor de Induccion')], max_length=100)),
                ('potencia', models.PositiveSmallIntegerField()),
                ('rango', models.PositiveSmallIntegerField()),
                ('capacidad_bateria', models.PositiveSmallIntegerField()),
                ('tiempo_carga', models.PositiveSmallIntegerField()),
                ('velocidad_maxima', models.PositiveSmallIntegerField()),
                ('frenos', models.CharField(choices=[('D4X4', 'Frenos de Disco en las Cuatro Ruedas'), ('D4x2', 'Frenos de Tambor en las Ruedas Traseras'), ('EBA', 'Emergency Brake Assist'), ('ABS', 'Antiblockiersystem')], max_length=100)),
                ('suspension', models.CharField(choices=[('SI4x4', 'Suspension Independiente en las Cuatro Ruedas'), ('SI2x4', 'Suspension de Doble Horquilla en la Parte Delantera'), ('SMP', 'Suspension MacPherson')], max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'vehiculo',
                'unique_together': {('modelo', 'year')},
            },
        ),
    ]
