# Generated by Django 4.2.1 on 2023-06-07 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('bodywork', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'Suv'), ('CROSSOVER', 'Crossover'), ('FURGONETA', 'Furgoneta')], max_length=50)),
                ('doors', models.PositiveSmallIntegerField()),
                ('motor', models.CharField(choices=[('SIP', 'Motor Electrico Sincrono de Imanes Permanentes'), ('CC', 'Motor Electrico de Corriente Continua'), ('I', 'Motor de Induccion')], max_length=100)),
                ('potency', models.PositiveSmallIntegerField()),
                ('range', models.PositiveSmallIntegerField()),
                ('battery_capacity', models.PositiveSmallIntegerField()),
                ('charging_time', models.PositiveSmallIntegerField()),
                ('top_speed', models.PositiveSmallIntegerField()),
                ('brakes', models.CharField(choices=[('D4X4', 'Frenos de Disco en las Cuatro Ruedas'), ('D4x2', 'Frenos de Tambor en las Ruedas Traseras'), ('EBA', 'Emergency Brake Assist'), ('ABS', 'Antiblockiersystem')], max_length=100)),
                ('suspension', models.CharField(choices=[('SI4x4', 'Suspension Independiente en las Cuatro Ruedas'), ('SI2x4', 'Suspension de Doble Horquilla en la Parte Delantera'), ('SMP', 'Suspension MacPherson')], max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.vehicle')),
            ],
            options={
                'db_table': 'vehicle_sucursal',
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='vehicles',
            field=models.ManyToManyField(blank=True, through='sucursal.VehicleSucursal', to='sucursal.vehicle'),
        ),
    ]
