# Generated by Django 4.2.1 on 2023-05-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_gerente', models.CharField(max_length=10)),
                ('cedula_jefe_taller', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
    ]
