# Generated by Django 4.2.1 on 2023-06-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='sucursal',
        ),
        migrations.CreateModel(
            name='VehicleSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.vehicle')),
            ],
            options={
                'db_table': 'vehicle_sucursal',
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='vehicles',
            field=models.ManyToManyField(blank=True, through='sucursal.VehicleSucursal', to='sucursal.vehicle'),
        ),
    ]
