# Generated by Django 4.2.1 on 2023-06-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0003_alter_vehiclesucursal_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclesucursal',
            unique_together={('vehicle', 'sucursal', 'color')},
        ),
    ]
