# Generated by Django 4.2.1 on 2023-06-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0005_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.part')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
            ],
            options={
                'db_table': 'sucursal_part',
                'unique_together': {('sucursal', 'part')},
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='parts',
            field=models.ManyToManyField(blank=True, through='sucursal.SucursalPart', to='sucursal.part'),
        ),
    ]
