# Generated by Django 4.2.1 on 2023-06-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0007_alter_sucursalpart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursalpart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.part'),
        ),
    ]
