# Generated by Django 4.2.1 on 2023-05-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sucursal.sucursal', to_field='cedula_gerente')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gerente',
            },
        ),
        migrations.CreateModel(
            name='JefeTaller',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sucursal.sucursal', to_field='cedula_jefe_taller')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'jefe_taller',
            },
        ),
    ]
