# Generated by Django 4.2.1 on 2023-05-20 19:19

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('date_joined', models.DateTimeField()),
                ('rol', models.CharField(choices=[('G', 'Gerente'), ('C', 'Cliente'), ('JT', 'Jefe Taller'), ('V', 'Vendedor')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sucursal.sucursal', to_field='cedula_gerente')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gerente',
            },
        ),
        migrations.CreateModel(
            name='JefeTaller',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sucursal.sucursal', to_field='cedula_jefe_taller')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'jefe_taller',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
