# Generated by Django 4.2.1 on 2023-06-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=10),
        ),
    ]
