# Generated by Django 4.2.1 on 2023-05-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contraseña',
            new_name='password',
        ),
    ]
