# Generated by Django 4.2.1 on 2023-06-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
        ('usuario', '0002_alter_user_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to='sucursal.sucursal'),
        ),
    ]
