# Generated by Django 4.2.1 on 2023-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Gerente', 'G'), ('Cliente', 'C'), ('JefeTaller', 'JT'), ('Vendedor', 'V')], max_length=15),
        ),
    ]
