# Generated by Django 4.2.1 on 2023-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('frenos_abs', models.BooleanField()),
                ('asientos', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('traccion', models.CharField(max_length=200)),
                ('velocidad_maxima', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('velocidades', models.IntegerField()),
            ],
        ),
    ]
